site_name: Lanbao's Blog
repo_url: https://github.com/lanbaoshen/blog
repo_name: lanbaoshen/blog

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt

plugins:
  - search
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lanbaoshen

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

nav:
  - Welcome: index.md
  - Automated Testing:
      - Accessibility Conflict: automated/accessibility-conflict.md
  - Python:
      - Capturing Grep Real-Time Output: python/capturing-grep-real-time-output.md
      - BFS and DFS in Dict Traversal: python/bfs-and-dfs-in-dict-traversal.md
      - Source Code Batch Changes: python/source-code-batch-changes.md
      - Stop or Kill a Thread: python/stop-or-kill-a-thread.md
      - Circular Import: python/circular-import.md
  - Repositories: repo/index.md
